/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Location {
  'country' : string,
  'city' : string,
  'address' : string,
}
export interface Parcel {
  'status' : ParcelStatus,
  'matchedTraveler' : [] | [Principal],
  'description' : string,
  'parcelType' : string,
  'sender' : Principal,
  'dropLocation' : Location,
  'priceOffered' : bigint,
  'pickupLocation' : Location,
}
export type ParcelStatus = { 'requested' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export type Time = bigint;
export interface Trip {
  'active' : boolean,
  'capacityDescription' : string,
  'toLocation' : Location,
  'traveler' : Principal,
  'fromLocation' : Location,
  'travelDate' : Time,
}
export interface UserProfile {
  'blocked' : boolean,
  'name' : string,
  'completedDeliveries' : bigint,
  'rating' : number,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptParcel' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, string], undefined>,
  'getAllParcels' : ActorMethod<[], Array<Parcel>>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchingParcelsForTrip' : ActorMethod<
    [Location, Location],
    Array<Parcel>
  >,
  'getMatchingTripsForParcel' : ActorMethod<[Location, Location], Array<Trip>>,
  'getMyParcels' : ActorMethod<[], Array<Parcel>>,
  'getMyTrips' : ActorMethod<[], Array<Trip>>,
  'getOwnProfile' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postParcel' : ActorMethod<
    [Location, Location, string, bigint, string],
    undefined
  >,
  'postTrip' : ActorMethod<[Location, Location, Time, string], undefined>,
  'rateUser' : ActorMethod<[Principal, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateParcelStatus' : ActorMethod<[bigint, ParcelStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];