/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ParcelStatus = IDL.Variant({
  'requested' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Location = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'address' : IDL.Text,
});
export const Parcel = IDL.Record({
  'status' : ParcelStatus,
  'matchedTraveler' : IDL.Opt(IDL.Principal),
  'description' : IDL.Text,
  'parcelType' : IDL.Text,
  'sender' : IDL.Principal,
  'dropLocation' : Location,
  'priceOffered' : IDL.Nat,
  'pickupLocation' : Location,
});
export const Time = IDL.Int;
export const Trip = IDL.Record({
  'active' : IDL.Bool,
  'capacityDescription' : IDL.Text,
  'toLocation' : Location,
  'traveler' : IDL.Principal,
  'fromLocation' : Location,
  'travelDate' : Time,
});
export const UserProfile = IDL.Record({
  'blocked' : IDL.Bool,
  'name' : IDL.Text,
  'completedDeliveries' : IDL.Nat,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptParcel' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchingParcelsForTrip' : IDL.Func(
      [Location, Location],
      [IDL.Vec(Parcel)],
      ['query'],
    ),
  'getMatchingTripsForParcel' : IDL.Func(
      [Location, Location],
      [IDL.Vec(Trip)],
      ['query'],
    ),
  'getMyParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'getMyTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getOwnProfile' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postParcel' : IDL.Func(
      [Location, Location, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'postTrip' : IDL.Func([Location, Location, Time, IDL.Text], [], []),
  'rateUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateParcelStatus' : IDL.Func([IDL.Nat, ParcelStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ParcelStatus = IDL.Variant({
    'requested' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Location = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'address' : IDL.Text,
  });
  const Parcel = IDL.Record({
    'status' : ParcelStatus,
    'matchedTraveler' : IDL.Opt(IDL.Principal),
    'description' : IDL.Text,
    'parcelType' : IDL.Text,
    'sender' : IDL.Principal,
    'dropLocation' : Location,
    'priceOffered' : IDL.Nat,
    'pickupLocation' : Location,
  });
  const Time = IDL.Int;
  const Trip = IDL.Record({
    'active' : IDL.Bool,
    'capacityDescription' : IDL.Text,
    'toLocation' : Location,
    'traveler' : IDL.Principal,
    'fromLocation' : Location,
    'travelDate' : Time,
  });
  const UserProfile = IDL.Record({
    'blocked' : IDL.Bool,
    'name' : IDL.Text,
    'completedDeliveries' : IDL.Nat,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptParcel' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchingParcelsForTrip' : IDL.Func(
        [Location, Location],
        [IDL.Vec(Parcel)],
        ['query'],
      ),
    'getMatchingTripsForParcel' : IDL.Func(
        [Location, Location],
        [IDL.Vec(Trip)],
        ['query'],
      ),
    'getMyParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'getMyTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getOwnProfile' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postParcel' : IDL.Func(
        [Location, Location, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'postTrip' : IDL.Func([Location, Location, Time, IDL.Text], [], []),
    'rateUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateParcelStatus' : IDL.Func([IDL.Nat, ParcelStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };